/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        orbitron: ['Orbitron', 'sans-serif'],
        rajdhani: ['Rajdhani', 'sans-serif'],
        mono: ['Share Tech Mono', 'monospace'],
        display: ['Orbitron', 'sans-serif'],
        body: ['Rajdhani', 'sans-serif'],
        label: ['Share Tech Mono', 'monospace'],
        terminal: ['Share Tech Mono', 'monospace'],
      },
      colors: {
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1c1b1d',
        'surface-container': '#201f22',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#d3c5ac',
        'inverse-surface': '#e5e1e4',
        'inverse-on-surface': '#313032',
        outline: '#9c8f79',
        'outline-variant': '#4f4633',
        'surface-tint': '#f9bd22',
        primary: '#ffe1a7',
        'on-primary': '#402d00',
        'primary-container': '#fbbf24',
        'on-primary-container': '#6c4f00',
        'inverse-primary': '#795900',
        secondary: '#d3fbff',
        'on-secondary': '#00363a',
        'secondary-container': '#00eefc',
        'on-secondary-container': '#00686f',
        tertiary: '#b6edff',
        'on-tertiary': '#003641',
        'tertiary-container': '#34daff',
        'on-tertiary-container': '#005c6e',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdf9f',
        'primary-fixed-dim': '#f9bd22',
        'on-primary-fixed': '#261a00',
        'on-primary-fixed-variant': '#5c4300',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#00dbe9',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        'tertiary-fixed': '#afecff',
        'tertiary-fixed-dim': '#30d8fd',
        'on-tertiary-fixed': '#001f27',
        'on-tertiary-fixed-variant': '#004e5d',
        background: '#131315',
        'on-background': '#e5e1e4',
        'surface-variant': '#353437',
        'neon-green': '#39ff14',
        'cyber-purple': '#b847ff',
        'zinc-900': '#18181b',
        'glass-border': 'rgba(255, 255, 255, 0.2)',
        'neon-cyan': '#00f0ff',
        'neon-amber': '#fbbf24',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '120px',
        'margin-mobile': '16px',
        'margin-desktop': '80px',
        unit: '4px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glow: '0 0 15px rgba(251, 191, 36, 0.2)',
        'glow-lg': '0 0 35px rgba(251, 191, 36, 0.6)',
        'glow-cyan': '0 0 15px rgba(0, 238, 252, 0.2)',
        'glow-cyan-lg': '0 0 35px rgba(0, 238, 252, 0.6)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'data-pulse': {
          '0%': { boxShadow: '0 0 0 0 rgba(251, 191, 36, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(251, 191, 36, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(251, 191, 36, 0)' },
        },
        wave: {
          '0%, 100%': { height: '4px' },
          '50%': { height: '16px' },
        },
        flux: {
          '0%': { transform: 'translate(0, 0) scale(0.5)', opacity: '0' },
          '20%': { opacity: '0.8' },
          '80%': { opacity: '0.8' },
          '100%': { transform: 'translate(var(--tx), var(--ty)) scale(1.5)', opacity: '0' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'spin-slow-reverse': {
          from: { transform: 'rotate(360deg)' },
          to: { transform: 'rotate(0deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', filter: 'drop-shadow(0 0 10px rgba(251, 191, 36, 0.5))' },
          '50%': { opacity: '.7', filter: 'drop-shadow(0 0 20px rgba(251, 191, 36, 0.8))' },
        },
        'core-pulse': {
          '0%': { transform: 'scale(0.95)', fill: '#00f0ff', filter: 'drop-shadow(0 0 15px rgba(0, 240, 255, 0.6))' },
          '100%': { transform: 'scale(1.05)', fill: '#fbbf24', filter: 'drop-shadow(0 0 30px rgba(251, 191, 36, 0.9))' },
        },
        'float-right': {
          '0%': { transform: 'translateX(-100vw)' },
          '100%': { transform: 'translateX(100vw)' },
        },
        'float-left': {
          '0%': { transform: 'translateX(100vw)' },
          '100%': { transform: 'translateX(-100vw)' },
        },
        'scroll-down': {
          '0%': { transform: 'translateY(0)', opacity: '0' },
          '50%': { transform: 'translateY(10px)', opacity: '1' },
          '100%': { transform: 'translateY(20px)', opacity: '0' },
        },
        flicker: {
          '0%': { opacity: '0' },
          '10%': { opacity: '0.5' },
          '20%': { opacity: '0' },
          '30%': { opacity: '1' },
          '40%': { opacity: '0.2' },
          '50%': { opacity: '1' },
          '60%': { opacity: '0.8' },
          '70%': { opacity: '1' },
          '80%': { opacity: '0.9' },
          '100%': { opacity: '1' },
        },
        glitch: {
          '0%': { transform: 'translate(0) skew(0deg)', opacity: '0' },
          '20%': { transform: 'translate(-2px, 2px) skew(-10deg)', opacity: '0.5' },
          '40%': { transform: 'translate(-2px, -2px) skew(10deg)', opacity: '0.8' },
          '60%': { transform: 'translate(2px, 2px) skew(-5deg)', opacity: '1' },
          '80%': { transform: 'translate(2px, -2px) skew(5deg)' },
          '100%': { transform: 'translate(0) skew(0deg)', opacity: '1' },
        },
        scan: {
          '0%': { left: '-100%' },
          '100%': { left: '200%' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        blink: 'blink 1s step-end infinite',
        'data-pulse': 'data-pulse 2s infinite',
        wave: 'wave 1.2s ease-in-out infinite',
        flux: 'flux var(--duration, 10s) ease-out var(--delay, 0s) infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'spin-slow-reverse': 'spin-slow-reverse 25s linear infinite',
        'spin-fast': 'spin-slow 10s linear infinite',
        'spin-reverse': 'spin-slow-reverse 15s linear infinite',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'core-pulse': 'core-pulse 1.5s ease-in-out infinite alternate',
        'float-right': 'float-right var(--duration, 35s) linear infinite',
        'float-left': 'float-left var(--duration, 30s) linear infinite',
        'scroll-down': 'scroll-down 1.5s ease-in-out infinite',
        flicker: 'flicker 2s linear forwards',
        glitch: 'glitch 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        scan: 'scan 1.5s cubic-bezier(0.4, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
